### ISSUE TITLE
Programme ne se lance pas + error code

### ISSUE THREAD

**Issue by ElTande** [Laiteux/Milky#12]
Bonjour, je me permet d'écrire en français car mon anglais est pas térible...
J'ai voulu tester milky avec un de tes exemples (le checker Club_Cooee) et j'obtiens ce message d'erreur en lançant le programme : 
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Milky.Models.Combo..ctor(String combo)
   at Milky_Examples.Club_Cooee_Checker.<>c.<Main>b__1_0(String combo) in C:\Users\Jojoyaknow\Desktop\Program.cs:line 21
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Milky_Examples.Club_Cooee_Checker.Main() in C:\Users\Jojoyaknow\Desktop\Program.cs:line 20
   at Milky_Examples.Club_Cooee_Checker.<Main>()
```
J'ai chercher comme je pouvais de mon côter, je ne m'y connais que très peux en c# donc mes compétences sont limités, désolé si la question peut paraître simple.

**Comment by BHNHAT** [comment]
Check your combos
It have some illegal string

**Comment by ElTande** [comment]
> Check your combos
> It have some illegal string

Ok, imma look at it, thanks !

**Comment by Laiteux** [comment]
Or simply parse combos, remove invalids right in your code, do whatever you want

**Comment by Laiteux** [comment]
Fixed with Milky v3, no need to parse combos yourself anymore, invalid ones will automatically get removed.
